apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice2-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webservice2
  template:
    metadata:
      labels:
        app: webservice2
    spec:
      containers:
      - name: webservice2
        image: webservice2
        imagePullPolicy: Never
        ports:
        - containerPort: 5000